import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { EnterIcon } from "../components/icons/EnterIcon";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kovalenko</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#FF8221] to-[#FF8221]">
        <header className="flex justify-start bg-transparent">
          <nav>
            <ul className="flex space-x-4 text-white">
              <li><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
            </ul>
          </nav>
        </header>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <div className="section-head">
            <h1 className="do-title text-left text-5xl font-extralight tracking-tight text-white sm:text-[5rem]">
              Kovalenko (dankaorange)
            </h1>
            <p className="max-w-lg text-left text-white font-extralight text-lg">
              Hi there! I am a UI/UX designer based in Prague. My main goal is
              to create better experiences through design. I am passionate about
              learning new technologies and have a personal and professional
              drive to shape products from a UX viewpoint, with a focus on
              quality, usability, and simplicity.
            </p>
          </div>
          {/* <p className="text-white">
            <a
              href="/resume.pdf"
              className="inline-block rounded border-2 border-gray-200 px-6 py-2 text-xs font-medium uppercase leading-tight text-gray-200 transition duration-150 ease-in-out hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0"
            >
              View Resume
              </a>
            </p> */}
        </div>
      </main>
      <section className="flex min-h-screen flex-col items-center justify-center bg-black">
        <div className="container flex flex-cols-1 flex-wrap gap-4 sm:flex-cols-2 md:gap-8 justify-around">
          <Link href="/work/nftliithos" className="do-card-wrap">
            <h3 className="text-2xl font-bold text-white">NFT Liithos →</h3>
            <div className="do-card relative max-w-md overflow-hidden rounded-xl bg-cover bg-no-repeat">
              <img
                src="/images/nft-thumb.png"
                className="do-card-img max-w-md transition duration-300 ease-in-out hover:scale-110"
                alt="Louvre"
              />
              <div className="do-card-gradient"></div>
              <div className="do-card-go">
                <EnterIcon />
              </div>
            </div>
          </Link>

          <Link href="/work/kalimera" className="do-card-wrap">
            <h3 className="text-2xl font-bold text-white">Kalimera →</h3>
            <div className="do-card relative max-w-md overflow-hidden rounded-xl bg-cover bg-no-repeat">
              <img
                src="/images/kalimera-thumb.png"
                className="do-card-img max-w-md transition duration-300 ease-in-out hover:scale-110"
                alt="Louvre"
              />
              <div className="do-card-gradient"></div>
              <div className="do-card-go">
                <EnterIcon />
              </div>
            </div>
          </Link>
        </div>
      </section>
    </>
  );
};

export default Home;
