import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const WorkPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kovalenko - Work</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#FF8221] to-[#8E4913]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold text-center tracking-tight text-white sm:text-[5rem]">
            Work
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          <Link
              href="/work/nftliithos"
            >
              <h3 className="text-2xl font-bold text-white">NFT Liithos →</h3>
              <div className="relative overflow-hidden bg-no-repeat bg-cover max-w-xs rounded-xl">
                <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/113.webp" className="max-w-xs hover:scale-110 transition duration-300 ease-in-out" alt="Louvre" />
              </div>
            </Link>
            <Link
              href="/work/kalimera"
            >
              <h3 className="text-2xl font-bold text-white">Kalimera →</h3>
              <div className="relative overflow-hidden bg-no-repeat bg-cover max-w-xs rounded-xl">
                <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/113.webp" className="max-w-xs hover:scale-110 transition duration-300 ease-in-out" alt="Louvre" />
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default WorkPage;
