import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const KalimeraPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kovalenko - Kalimera</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#FF8221] to-[#8E4913]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold text-center tracking-tight text-white sm:text-[5rem]">
            Kalimera
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          
          </div>
        </div>
      </main>
    </>
  );
};

export default KalimeraPage;
